name: renv_nifh_analysis
channels:
  - conda-forge
  - bioconda
dependencies:
  - r-base=4.4.2
  - r-tidyverse=2.0.0
  - r-patchwork=1.3.0
  - r-argparser=0.7.2
  - r-rlang=1.1.4
  - r-maps=3.4.2.1
  - r-roxygen2=7.3.2
  - r-rcolorbrewer=1.1_3
