# _#  Snakefile file to mange the CMAP stage of the nifH ASV workflow ##
# _#  Configfile is used to supply parameters to Snakefile ##

##  CMAP Data Colocalization ##
##  Description:
##      Colocalizes input data with the Simon's Collaborative Marine Atlas
##      Project (CMAP) data repository to retrieve environmental data
##      of interest to be used in analysis. The output is a compress csv file
##      of the colocalized dataset.
##
##  Calls script: query_cmap.py
##      Takes CSV of the nifH amplicon sample collection data from the
##      GatherMetadata stage (metadata.cmap.csv containing lat, lon, time, and
##      depth) as input, colocalizes this with specified targets in the CMAP
##      catalog, producing a compressed CSV file with environment data of
##      interest.
##
##  Parameters are passed via a config file
##!  ############ MODIFICATION OF THIS FILE (config.json) #############
##!  ########################## IS REQUIRE ###########################
##!  Configfile: config.json
##!     MODIFY "api_key": "*******YOU_API_KEY_HERE*******" TO BE YOUR API KEY
##!     as described at: https://simonscmap.com/apikeymanagement
##
##  After the addition of your API key to the config file, the workflow can be
##  run as shown below in Usage.
##
##  Conda environment:
##      A conda environment is created that encasulates all the necessary
##      libraries/packages and tools required to run the query_cmap.py script.
##      Running the snakefile will make this conda environment using file:
##      CMAP/environments/CMAP_enviroments.yaml
##
##  A more detailed explaination of the script 'query_cmap.py' and all that it ##  does can be found in the documentation within the script itself. Most of
##  these detials can also be accessed by running the script with itself with ##  the help argument:
##  query_cmap.py --help
##
##
##  Usage:
##    snakemake -c1 --use-conda         # Default. Retrieve CMAP data if
##                                        metadata.cmap.tsv changed.
##    snakemake -c1 clean               # Remove CMAP_metadata.csv.gz
##    snakemake -c1 superclean          # Remove CMAP_metadata.csv.gz, log
##                                        directory, and CMAP conda environment
##
##


# Import the datetime module
import datetime

# Author, copyright, maintainer, email, and status metadata
__author__ = "Michael (Mo) Morando"
__copyright__ = "Copyright 2023"
__maintainer__ = "Michael (Mo) Morando"
__email__ = "mikemo@gmail.com"
__status__ = "Stable"


# Load parameters from JSON config
#! A nasty error is thrown if you do not add your API key to the JSON config
#! file and this helps make that easier to understand
try:
    configfile: "config.json"
    api_key = config.get("api_key")
    if not api_key:
        raise KeyError("Your API key is missing in the config file.")
except FileNotFoundError:
    print("Error: Config file 'config.json' not found!")
    exit(1)
except KeyError as e:
    print(f"Error: {e}")
    exit(1)

# Function to generate a timestamp
def get_timestamp():
    return datetime.datetime.now().strftime("%Y%m%d")


# Rule to query CMAP
rule query_CMAP:
    input:
        config["input_path"],
    output:
        config["output_path"],
    params:
        api_key=api_key,
    log:
        expand(
            "logs/query_cmap_{timestamp}.log",
            timestamp=get_timestamp(),
        ),
    conda:
        "environments/CMAP_enviroments.yaml"
    shell:
        """
        python3 scripts/query_cmap.py {input} {output} {params.api_key} > {log} 2>&1
        """


# Cleaning rules
rule clean:
    shell:
        """
        echo "Cleaning output files only"
        snakemake -c 1 --use-conda --delete-all-output
        """


rule superclean:
    shell:
        """
        echo "Cleaning all output files and directories"
        echo "Removing conda environment made by this snakefile"
        snakemake -c 1 --use-conda --delete-all-output
        # Check if directory exists before removing it
        if [ -d logs ]; then
            rm -rf logs
            echo "Directory 'logs' removed"
        fi
        # Check if directory exists before removing it
        if [ -d .snakemake/conda ]; then
            rm -r .snakemake/conda/
            echo "Conda environment removed"
        fi
        """
