## Copyright (C) 2023 Jonathan D. Magasin
##
## This file describes packages required to run the nifH ASV workflow.
##
## Maintainer notes:
## This yml must mirror the DADA nifH pipeline's environment_DADA2_nifH_with_ancillary.yml, and add
## the few additional workflow-specific packages in the final section. Mirroring is not ideal but is
## safer/simpler for the user compared to cloning DADA2_nifH and adding each additional package
## needed by the workflow.
##
## Note also that an earlier solution was to --stack nifH_ASV_workflow on top of DADA2_nifH. However,
## that only works for conda packages.  R and python libraries installed in DADA2_nifH would
## disappear if there was an R or python in nifH_ASV_workflow (and my workaround, adding them to
## DADA2_nifH, was a hack).
##
## The specified package verions were used when creating the nifH ASV database described in
## Morando and Magasin et al., 2024 in Earth System Science Data.
##
name: nifH_ASV_workflow
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  # Core DADA2 nifH pipeline
  - r-base             =4.3.3
  - bioconductor-dada2 =1.30.0
  - r-vegan            =2.6_8
  - cutadapt           =4.9
  - fraggenescan       =1.31
  - hmmer              =3.4

  # DADA2 nifH pipeline ancillary scripts
  #                             Needed by:
  - r-digest           =0.6.37 #  assignAUIDs2ASVs.R
  - fastqc             =0.12.1 #  do_fastqc.sh
  - vsearch            =2.28.1 #  check_chimera_denovo.sh
  - blast              =2.16.0 #  check_nifH_contaminants.sh, classifyNifH.sh, blast{nARB2017,xGenome879}.sh
  - biopython          =1.84   #  assignNifHclustersToNuclSeqs.sh
  - mafft              =7.526  #  assignNifHclustersToNuclSeqs.sh

  # External tools required by the ASV workflow
  #                             Needed by:
  - make               =4.4.1  #  Most stages use Makefiles
  - snakemake          =8.20.7 #  CMAP stage uses Snakemake
  - pandas             =2.1.2  #  AnnotateAuids
  - r-lutz             =0.3.2  #  GatherMetadata
  - r-tidyverse        =2.0.0  #  WorkspaceStartup
