descrption: |
  Configuration file for nifh_amplicons_analysis workflow

  This YAML file contains configuration settings for the Snakemake workflow
  that processes and analyzes NifH amplicon data. It defines input and output
  paths, file names, and parameters used throughout the pipeline.

  Main sections:
  1. Environment settings
  2. Input/Output directories
  3. File lists for various processing stages
  4. Plotting parameters
  5. Input/Output file lists for specific analysis steps

  Usage:
      This file should be named 'config.yaml' and placed in the same directory
      as the Snakefile. It will be automatically loaded by Snakemake.

metadata:
  author: "Michael (Mo) Morando"
  last_updated: "2025-02-02"

# Conda enviroment
conda_env: "../environments/environment.yaml"

# Input files
workspace: "../data/workspace/Sep18/workspace.RData"
input_dir_tables: "../data/csvs_for_tables"

# Output directories
output_dir: "../analysis/out_files"
plot_dir: "../analysis/plots"
table_dir: "../analysis/tables"

# Files to process
files_to_process:
  - annoNifHDB_updt
  - cmap_coloc
  - nifhDB_cnts
  - nifhDB_RA
  - metaTab

# Files out: processing
# Files in: basic_samp_stats.R
files_out_process:
  # - cmap_coloc  # !  cannot have the same name of a file as input and output for a snakefile!!
  # - annoNifHDB_updt
  - counts_df_T_lng
  - counts_df_T_lng_AUID_deduped
  - counts_df_T_AUID_deduped
  - counts_df_AUID_deduped
  - DNA_samples_key
  - unique_sample_id_key
  - photic_samples_key
  - RA_df_T_lng
  - RA_df_T_lng_mean_RA_AUID_deduped
  - RA_df_T_mean_RA_AUID_deduped
  - RA_df_mean_RA_AUID_deduped

# Files in for parameters basic_samp_stats.R
files_in_bss:
  - counts_df_T_lng
  - counts_df_T_lng_AUID_deduped
  - cmap_coloc
  - unique_sample_id_key
  - photic_samples_key
  - DNA_samples_key

# Files out for basic_samp_stats.R
files_out_bss:
  - samples_per_nucleicAcidType
  - samples_per_nucleicAcidType_studyid
  - samples_per_photic
  - samples_per_photic_nucacid
  - sample_type

# Files in for samp_tax_brkdwn.R
files_in_stb:
  - counts_df_T_lng_AUID_deduped,
  - RA_df_T_lng_mean_RA_AUID_deduped,
  - cmap_coloc,
  - annoNifHDB_updt,
  - unique_sample_id_key,
  - photic_samples_key,
  - DNA_samples_key

# Files in for samp_tax_brkdwn.R
files_out_stb:
  - nifhdb_all_counts_AUID_dedup_study_id_total
  - nifhdb_all_counts_AUID_dedup_clean
  - nifhdb_all_counts_AUID_dedup_total_study_id_clean
  - nifhdb_all_counts_AUID_dedup_study_id_total_clean
  - nifhdb_all_rel_abund_AUID_dedup_study_id_total
  - nifhdb_all_rel_abund_AUID_dedup_clean
  - nifhdb_all_rel_abund_AUID_dedup_total_study_id_clean
  - nifhdb_all_rel_abund_AUID_dedup_study_id_total_clean

# Files in for plots_out.R
files_in_plot:
  - samples_per_nucleicAcidType
  - samples_per_nucleicAcidType_studyid
  - samples_per_photic
  - samples_per_photic_nucacid
  - sample_type
  - unique_sample_id_key
  - cmap_coloc

# Files out for plots_out.R
files_out_plot:
  - samp_nucleic_acid_type_light_bar_cmb_plot
  - Samples_per_studyID_ocean_fill_bar_facet_nucelic
  - Samples_per_ocean_hemi_fill_bar
  - Samples_per_month_bar
  - Samples_per_month_study_id_bar
  - Samples_per_abslat_hemi_hist
  - Samples_per_season_hemi_bar
  - Samples_per_depth_hemi_above150m_hist
  - Samples_per_depth_hemi_below150_hist
  - Samples_per_depth_hemi_hist_cmb_plot
  - Samples_per_SST_hemi_hist
  - Samples_per_PO4_hemi_hist
  # - Samples_per_abslat_ocean_sst_po4_hemi_cmb_hist
  - f05
  - Samples_per_logFe_hemi_hist
  - Samples_per_PP_tblPisces_NRT_hemi_hist
  - Samples_per_CHL_tblPisces_NRT_hemi_hist

# Plotting suffix/type
plot_ext: ".svg"
# plot_ext: ".jpeg"
# plot_ext: ".png"
# plot_ext: ".pdf"
# plot_device: "jpeg"
plot_device: "svg"
# plot_device: "png"
# plot_device: "cairo_pdf"

# Files in for plots_taxonomy.R
files_in_plot_tax:
  - nifhdb_all_counts_AUID_dedup_clean
  - nifhdb_all_rel_abund_AUID_dedup_clean
  - nifhdb_all_counts_AUID_dedup_total_study_id_clean
  - nifhdb_all_rel_abund_AUID_dedup_total_study_id_clean
  - nifhdb_all_rel_abund_AUID_dedup_study_id_total_clean
  - nifhdb_all_counts_AUID_dedup_study_id_total_clean
  - nifhdb_all_counts_AUID_dedup_study_id_total
  - nifhdb_all_rel_abund_AUID_dedup_study_id_total
  - RA_df_T_lng_mean_RA_AUID_deduped
  - cmap_coloc
  - annoNifHDB_updt

# Files in for plots_taxonomy.R
files_out_plot_tax:
  - DNA_perc_cnts_clst_all_bar
  - DNA_perc_cnts_clst_bar
  - DNA_perc_cnts_clst_pie
  - DNA_perc_combined_clst_pie
  # - DNA_perc_rel_abund_clst_all_bar
  - f07
  - DNA_perc_rel_abund_clst_bar
  - DNA_perc_rel_abund_clst_pie

files_in_tables:
  - Table_SreadsAtEachStage_samples
  - workflowTable

files_out_tables:
  - Table 4
  - Table 5

files_in_wrld_plt:
  - cmap_coloc

files_out_wrld_plt:
  - worldStnMap_nifhdb_allstudies
  - worldStnMap_nifhdb_allstudies_fct_ocean
