# config.yaml

# Input workspace
# workspace: "../data/workspace/archive/NifH_ASV_DB_March28_after_drop_19_empty_samples/workspace.RData"
workspace: "../data/workspace/Sep18/workspace.RData"

# Output directories
output_dir: "../analysis/out_files"
plot_dir: "../analysis/plots"

# Files to process
files_to_process:
  - annoNifHDB_updt
  - cmap_coloc
  - nifhDB_cnts
  - nifhDB_RA
  - metaTab

# Files out: processing
# Files in: basic_samp_stats.R
files_out_process:
  # - cmap_coloc  # !  cannot have the same name of a file as input and output for a snakefile!!
  # - annoNifHDB_updt
  - counts_df_T_lng 
  - counts_df_T_lng_AUID_deduped 
  - counts_df_T_AUID_deduped 
  - counts_df_AUID_deduped
  - DNA_samples_key
  - unique_sample_id_key
  - photic_samples_key 
  - RA_df_T_lng 
  - RA_df_T_lng_mean_RA_AUID_deduped 
  - RA_df_T_mean_RA_AUID_deduped 
  - RA_df_mean_RA_AUID_deduped 


# Files in for parameters basic_samp_stats.R
files_in_bss:
  - counts_df_T_lng
  - counts_df_T_lng_AUID_deduped
  - cmap_coloc
  - unique_sample_id_key
  - photic_samples_key
  - DNA_samples_key

# Files out for basic_samp_stats.R
files_out_bss:
  - samples_per_nucleicAcidType
  - samples_per_nucleicAcidType_studyid
  - samples_per_photic
  - samples_per_photic_nucacid
  - sample_type


# Files in for samp_tax_brkdwn.R
files_in_stb:
  - counts_df_T_lng_AUID_deduped,
  - RA_df_T_lng_mean_RA_AUID_deduped,
  - cmap_coloc,
  - annoNifHDB_updt,
  - unique_sample_id_key,
  - photic_samples_key,
  - DNA_samples_key

# Files in for samp_tax_brkdwn.R
files_out_stb:
  - nifhdb_all_counts_AUID_dedup_study_id_total 
  - nifhdb_all_counts_AUID_dedup_clean 
  - nifhdb_all_counts_AUID_dedup_total_study_id_clean 
  - nifhdb_all_counts_AUID_dedup_study_id_total_clean 
  - nifhdb_all_rel_abund_AUID_dedup_study_id_total 
  - nifhdb_all_rel_abund_AUID_dedup_clean 
  - nifhdb_all_rel_abund_AUID_dedup_total_study_id_clean 
  - nifhdb_all_rel_abund_AUID_dedup_study_id_total_clean 


# Files in for plots_out.R
files_in_plot:
  - samples_per_nucleicAcidType
  - samples_per_nucleicAcidType_studyid
  - samples_per_photic
  - samples_per_photic_nucacid
  - sample_type
  - unique_sample_id_key
  - cmap_coloc


# Files out for plots_out.R
files_out_plot:
  - samp_nucleic_acid_type_light_bar_cmb_plot
  - Samples_per_studyID_ocean_fill_bar_facet_nucelic
  - Samples_per_ocean_hemi_fill_bar
  - Samples_per_month_bar
  - Samples_per_month_study_id_bar
  - Samples_per_abslat_hemi_hist
  - Samples_per_season_hemi_bar
  - Samples_per_depth_hemi_above150m_hist
  - Samples_per_depth_hemi_below150_hist
  - Samples_per_depth_hemi_hist_cmb_plot
  - Samples_per_SST_hemi_hist
  - Samples_per_PO4_hemi_hist
  - Samples_per_abslat_ocean_sst_po4_hemi_cmb_hist
  - Samples_per_logFe_hemi_hist
  - Samples_per_PP_tblPisces_NRT_hemi_hist
  - Samples_per_CHL_tblPisces_NRT_hemi_hist

# Plotting suffix/type
plot_ext: ".svg"


# Files in for plots_taxonomy.R
files_in_plot_tax:
  - nifhdb_all_counts_AUID_dedup_clean
  - nifhdb_all_rel_abund_AUID_dedup_clean
  - nifhdb_all_counts_AUID_dedup_total_study_id_clean
  - nifhdb_all_rel_abund_AUID_dedup_total_study_id_clean
  - nifhdb_all_rel_abund_AUID_dedup_study_id_total_clean
  - nifhdb_all_counts_AUID_dedup_study_id_total_clean
  - nifhdb_all_counts_AUID_dedup_study_id_total
  - nifhdb_all_rel_abund_AUID_dedup_study_id_total

# Files in for plots_taxonomy.R
files_out_plot_tax:
  - DNA_perc_cnts_clst_all_bar 
  - DNA_perc_cnts_clst_bar 
  - DNA_perc_cnts_clst_pie 
  - DNA_perc_combined_clst_pie 
  - DNA_perc_rel_abund_clst_all_bar 
  - DNA_perc_rel_abund_clst_bar 
  - DNA_perc_rel_abund_clst_pie